source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0' # deployment target, i.e. lowest supported version
use_frameworks!

project 'Ua Mobile Keys', {
    'Debug' => :debug
}

def applibs
  pod 'SeosMobileKeysSDK-Debug', :configuration => ['Debug'], :path  => 'Mobile_Keys_IOS_SDK/Debug/SeosMobileKeysSDK-Debug.podspec'
end

# Apps

target 'Ua Mobile Keys' do
  workspace 'Ua Mobile Keys.xcworkspace'
  project 'Ua Mobile Keys.xcodeproj'
  applibs
end

post_install do | installer |
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end
end
